//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UminekoLauncher.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UminekoLauncher.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check your internet connection and try again later 的本地化字符串。
        /// </summary>
        public static string Check_Internet {
            get {
                return ResourceManager.GetString("Check Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the button to go to the download 的本地化字符串。
        /// </summary>
        public static string Click_Download {
            get {
                return ResourceManager.GetString("Click Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the button to automatically update 的本地化字符串。
        /// </summary>
        public static string Click_Update {
            get {
                return ResourceManager.GetString("Click Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sure to check game integrity? 的本地化字符串。
        /// </summary>
        public static string Confirm_Check {
            get {
                return ResourceManager.GetString("Confirm Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This version is free. It&apos;s your duty to support the original author. 的本地化字符串。
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Mode 的本地化字符串。
        /// </summary>
        public static string Display_Mode {
            get {
                return ResourceManager.GetString("Display Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the display mode used by the game. 的本地化字符串。
        /// </summary>
        public static string Display_Mode_Desciption {
            get {
                return ResourceManager.GetString("Display Mode Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading... 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading:  的本地化字符串。
        /// </summary>
        public static string Downloading2 {
            get {
                return ResourceManager.GetString("Downloading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something went wrong! Relevant important files were not detected, please check the game integrity. 的本地化字符串。
        /// </summary>
        public static string Error_Broken {
            get {
                return ResourceManager.GetString("Error Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hashing algorithm not supported. 的本地化字符串。
        /// </summary>
        public static string Error_Checksum {
            get {
                return ResourceManager.GetString("Error Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while communicating with the server. 的本地化字符串。
        /// </summary>
        public static string Error_Communication {
            get {
                return ResourceManager.GetString("Error Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game config not found. 的本地化字符串。
        /// </summary>
        public static string Error_Config {
            get {
                return ResourceManager.GetString("Error Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something went wrong! The launcher is already running. 的本地化字符串。
        /// </summary>
        public static string Error_Running {
            get {
                return ResourceManager.GetString("Error Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception:  的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File integrity check failed. 的本地化字符串。
        /// </summary>
        public static string Failed_Integrity_Check {
            get {
                return ResourceManager.GetString("Failed Integrity Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write feedback 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        public static string Full_Screen {
            get {
                return ResourceManager.GetString("Full Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest 的本地化字符串。
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start! Please check the game integrity and related settings. 的本地化字符串。
        /// </summary>
        public static string Launch_Failed {
            get {
                return ResourceManager.GetString("Launch Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legacy 的本地化字符串。
        /// </summary>
        public static string Legacy {
            get {
                return ResourceManager.GetString("Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legacy Opening 的本地化字符串。
        /// </summary>
        public static string Legacy_OP {
            get {
                return ResourceManager.GetString("Legacy OP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the opening version, will only affect EP1-4. 的本地化字符串。
        /// </summary>
        public static string Legacy_OP_Decription {
            get {
                return ResourceManager.GetString("Legacy OP Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading...
        ///
        ///To ensure the experience, it is recommended to wait for the detection to complete before starting the game. 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing necessary update fields. 的本地化字符串。
        /// </summary>
        public static string Missing_Field {
            get {
                return ResourceManager.GetString("Missing Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No updates available 的本地化字符串。
        /// </summary>
        public static string No_Update {
            get {
                return ResourceManager.GetString("No Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NS Ver 的本地化字符串。
        /// </summary>
        public static string NS_Version {
            get {
                return ResourceManager.GetString("NS Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PS3 的本地化字符串。
        /// </summary>
        public static string PS3 {
            get {
                return ResourceManager.GetString("PS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PS4 Ver 的本地化字符串。
        /// </summary>
        public static string PS4_Version {
            get {
                return ResourceManager.GetString("PS4 Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the screen resolution used for the game. 的本地化字符串。
        /// </summary>
        public static string Resolution_Description {
            get {
                return ResourceManager.GetString("Resolution Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the update cannot be solved by retrying, please give feedback 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set whether to scale when playing in full screen mode. 的本地化字符串。
        /// </summary>
        public static string Scale_Decription {
            get {
                return ResourceManager.GetString("Scale Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Ver 的本地化字符串。
        /// </summary>
        public static string Steam_Version {
            get {
                return ResourceManager.GetString("Steam Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun Never Sets Team 的本地化字符串。
        /// </summary>
        public static string Sun_Never_Sets_Team {
            get {
                return ResourceManager.GetString("Sun Never Sets Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit the CN translation team&apos;s website. 的本地化字符串。
        /// </summary>
        public static string Sun_Never_Sets_Team_Description {
            get {
                return ResourceManager.GetString("Sun Never Sets Team Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Umineko Project 的本地化字符串。
        /// </summary>
        public static string Umineko_Project {
            get {
                return ResourceManager.GetString("Umineko Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit the developers&apos; website. 的本地化字符串。
        /// </summary>
        public static string Uminkeo_Project_Description {
            get {
                return ResourceManager.GetString("Uminkeo Project Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updatable 的本地化字符串。
        /// </summary>
        public static string Updatable {
            get {
                return ResourceManager.GetString("Updatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not yet checked for updates. 的本地化字符串。
        /// </summary>
        public static string Update_Not_Checked {
            get {
                return ResourceManager.GetString("Update Not Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait 的本地化字符串。
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait for the update to complete 的本地化字符串。
        /// </summary>
        public static string Wait_Updating {
            get {
                return ResourceManager.GetString("Wait Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
